#pragma once
#define BLOBDET_VERSION_MAJOR    0
#define BLOBDET_VERSION_MINOR    1
#define BLOBDET_VERSION_REVISION 0

#define _STR_EXP(__A)  #__A
#define _STR(__A)      _STR_EXP(__A)

#define BLOBDET_VERSION _STR(BLOBDET_VERSION_MAJOR) "." _STR(BLOBDET_VERSION_MINOR) "." _STR(BLOBDET_VERSION_REVISION)
